# Makefile for stklos-gtk-base example 
#
#          Author: Erick Gallesio [eg@essi.fr]
#   Creation date:  8-Apr-2008 18:28 (eg)
#Last file update:  8-Apr-2008 18:31 (eg)

all: simple

simple: simple.stk
	stklos-compile -o simple simple.stk

clean:
	/bin/rm -f *~ simple
